#!/usr/bin/env python3
"""Validate the Mintlify docs-v2 site and generated Python API reference.

Checks:
  - docs.json parses and matches Mintlify's required shape
  - generated API reference is up to date (stale detection)
  - generation is deterministic (two consecutive runs match)
  - generated MDX files carry the do-not-edit banner
  - Mintlify build validation and broken-link detection
"""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1]
ROOT = DOCS.parent
API_DIR = DOCS / "api"
ROOT_PAGE = DOCS / "api-reference.mdx"
NAV_FILE = DOCS / "api-pages.json"
DOCS_JSON = DOCS / "docs.json"
GENERATE = DOCS / "scripts" / "generate_api.py"
BANNER_NEEDLE = "DO NOT EDIT. Generated by"


def _fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def check_docs_json() -> None:
    try:
        data = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        _fail(f"docs.json is not valid JSON: {exc}")

    for key in ("name", "theme", "colors", "navigation"):
        if key not in data:
            _fail(f"docs.json missing required field: {key}")
    if "primary" not in data.get("colors", {}):
        _fail("docs.json colors.primary is required")
    if not isinstance(data["navigation"], dict) or not data["navigation"]:
        _fail("docs.json navigation must be a non-empty object")
    print("ok: docs.json configuration")


def _generated_mdx_paths() -> list[Path]:
    paths = list(API_DIR.rglob("*.mdx")) if API_DIR.exists() else []
    if ROOT_PAGE.exists():
        paths.append(ROOT_PAGE)
    return sorted(paths)


def check_generated_banners() -> None:
    paths = _generated_mdx_paths()
    if not paths:
        _fail("no generated API MDX files found; run make docs-v2-api")
    missing = [
        p.relative_to(DOCS).as_posix()
        for p in paths
        if BANNER_NEEDLE not in p.read_text(encoding="utf-8")
    ]
    if missing:
        sample = ", ".join(missing[:8])
        suffix = "…" if len(missing) > 8 else ""
        _fail(
            "generated API files missing do-not-edit banner "
            f"(re-run make docs-v2-api): {sample}{suffix}"
        )
    print(f"ok: generated banners ({len(paths)} mdx files)")


def check_nav_shape() -> None:
    """Ensure nav uses short labels and package roots (no __init__ entries)."""
    if not NAV_FILE.exists():
        _fail(f"missing {NAV_FILE.relative_to(ROOT)}; run make docs-v2-api")
    nav = json.loads(NAV_FILE.read_text(encoding="utf-8"))
    if not nav or nav[0] != "api-reference":
        _fail("api-pages.json must start with api-reference (package __init__)")

    def walk(entry: object) -> None:
        if isinstance(entry, str):
            if "__init__" in entry or entry.startswith("python-api/"):
                _fail(f"stale nav path: {entry}")
            if "agentconnect" in entry:
                _fail(f"nav path still contains package prefix: {entry}")
            return
        if isinstance(entry, dict):
            group = entry.get("group", "")
            if isinstance(group, str) and group.startswith("agentconnect"):
                _fail(f"group label still prefixed: {group}")
            if "root" in entry and "__init__" in str(entry["root"]):
                _fail(f"root still points at __init__ path: {entry['root']}")
            for page in entry.get("pages", []):
                walk(page)

    for item in nav:
        walk(item)
    print("ok: API navigation shape (roots, short labels, no __init__ pages)")


def _snapshot(dest: Path) -> None:
    dest.mkdir(parents=True, exist_ok=True)
    if not NAV_FILE.exists():
        _fail(f"missing {NAV_FILE.relative_to(ROOT)}; run make docs-v2-api")
    shutil.copy2(NAV_FILE, dest / "api-pages.json")
    if ROOT_PAGE.exists():
        shutil.copy2(ROOT_PAGE, dest / "api-reference.mdx")
    api_dest = dest / "api"
    if api_dest.exists():
        shutil.rmtree(api_dest)
    if API_DIR.exists():
        shutil.copytree(API_DIR, api_dest)


def _trees_equal(left: Path, right: Path) -> list[str]:
    diffs: list[str] = []
    left_files = {
        p.relative_to(left).as_posix() for p in left.rglob("*") if p.is_file()
    }
    right_files = {
        p.relative_to(right).as_posix() for p in right.rglob("*") if p.is_file()
    }
    for rel in sorted(left_files | right_files):
        if rel not in left_files:
            diffs.append(f"only in regenerated: {rel}")
            continue
        if rel not in right_files:
            diffs.append(f"only in committed: {rel}")
            continue
        if not filecmp.cmp(left / rel, right / rel, shallow=False):
            diffs.append(f"content differs: {rel}")
    return diffs


def _restore_snapshot(snapshot: Path) -> None:
    if API_DIR.exists():
        shutil.rmtree(API_DIR)
    if (snapshot / "api").exists():
        shutil.copytree(snapshot / "api", API_DIR)
    shutil.copy2(snapshot / "api-pages.json", NAV_FILE)
    if (snapshot / "api-reference.mdx").exists():
        shutil.copy2(snapshot / "api-reference.mdx", ROOT_PAGE)
    elif ROOT_PAGE.exists():
        ROOT_PAGE.unlink()


def check_stale_and_deterministic(*, skip_deterministic: bool) -> None:
    if not API_DIR.exists() or not NAV_FILE.exists() or not ROOT_PAGE.exists():
        _fail("generated API reference missing; run make docs-v2-api")

    with tempfile.TemporaryDirectory(prefix="ac-docs-v2-") as tmp:
        tmp_path = Path(tmp)
        before = tmp_path / "before"
        after1 = tmp_path / "after1"
        after2 = tmp_path / "after2"
        _snapshot(before)

        try:
            subprocess.run([sys.executable, str(GENERATE)], check=True, cwd=ROOT)
            _snapshot(after1)
            if not skip_deterministic:
                subprocess.run([sys.executable, str(GENERATE)], check=True, cwd=ROOT)
                _snapshot(after2)
        finally:
            _restore_snapshot(before)

        stale = _trees_equal(before, after1)
        if stale:
            _fail(
                "generated API reference is stale; run `make docs-v2-api` and commit.\n"
                + "\n".join(stale[:20])
            )
        print("ok: generated API reference is up to date")

        if not skip_deterministic:
            drift = _trees_equal(after1, after2)
            if drift:
                _fail(
                    "API generation is not deterministic across consecutive runs.\n"
                    + "\n".join(drift[:20])
                )
            print("ok: API generation is deterministic")


def run_mint(script: str) -> None:
    npm = shutil.which("npm")
    if npm is None:
        _fail("npm is required for Mintlify checks")
    mint_bin = DOCS / "node_modules" / ".bin" / "mint"
    if not mint_bin.exists():
        print("+ npm ci", flush=True)
        subprocess.run([npm, "ci"], check=True, cwd=DOCS)
    print(f"+ npm run {script}", flush=True)
    subprocess.run([npm, "run", script], check=True, cwd=DOCS)
    print(f"ok: mint {script}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--skip-mint", action="store_true")
    parser.add_argument("--skip-deterministic", action="store_true")
    parser.add_argument("--mint-only", action="store_true")
    args = parser.parse_args(argv)

    if not args.mint_only:
        check_docs_json()
        check_generated_banners()
        check_nav_shape()
        check_stale_and_deterministic(skip_deterministic=args.skip_deterministic)

    if not args.skip_mint:
        run_mint("validate")
        run_mint("broken-links")

    print("all docs-v2 checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
