#!/usr/bin/env python3
"""Generate Mintlify MDX API reference from AgentConnect's public Python API.

Pipeline:
  1. mdxify (Griffe 2) discovers/public-API parses modules → temporary MDX
  2. Reshape files + navigation to match MCP/Typesafe-style package trees:
       - agentconnect.__init__ → api-reference.mdx (first API tab page)
       - package __init__ pages become group roots (no visible "__init__" entries)
       - strip the ``agentconnect.`` prefix from sidebar group labels
  3. Normalize docstring rendering (Args/Returns/Raises/Examples, code fences)
  4. Stamp generated files and write api-pages.json for docs.json $ref
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
DOCS = Path(__file__).resolve().parents[1]
API_DIR = DOCS / "api"
NAV_FILE = DOCS / "api-pages.json"
ROOT_PAGE = DOCS / "api-reference.mdx"
PACKAGE = "agentconnect"

EXCLUDE_PREFIXES = (
    "agentconnect.gateway",
    "agentconnect.utils",
    "agentconnect.index.registry.capability_discovery_impl",
)

GENERATED_BANNER = """\
{/* DO NOT EDIT. Generated by `make docs-v2-api` / docs-v2/scripts/generate_api.py.
    Handwritten docs live outside api/ and api-reference.mdx.
    Source: AgentConnect public Python modules via mdxify + Griffe 2. */}
"""

SOURCE_MARKER_RE = re.compile(
    r"\{/\* DO NOT EDIT\. Generated by.*?via mdxify \+ Griffe 2\. \*/\}\n?",
    re.DOTALL,
)
_FENCE_PATTERN = re.compile(r"```[\s\S]*?```")
_RST_DOUBLE_TICK = re.compile(r"``([^`]+)``")
_PLACEHOLDER_URL = re.compile(r"https?://\S*&lt;\S*")
_FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n*", re.DOTALL)

# Indented example / usage blocks that should become fenced Python.
# Allow blank lines between indented lines so multi-statement examples stay one fence.
_INDENTED_BLOCK_RE = re.compile(
    r"(?m)^(?P<body>(?:[ \t]{4,}|\t).+(?:\n(?:[ \t]*$|(?:[ \t]{4,}|\t).+))*)\n*",
)

_ARGS_SECTION_RE = re.compile(
    r"(?ms)^\*\*Args:\*\*\n(?P<body>.*?)(?=\n\n|\n\*\*[A-Z][a-z]+:\*\*|\n#{1,6} |\Z)",
)
_RETURNS_SECTION_RE = re.compile(
    r"(?ms)^\*\*Returns:\*\*\n(?P<body>.*?)(?=\n\n|\n\*\*[A-Z][a-z]+:\*\*|\n#{1,6} |\Z)",
)
_RAISES_SECTION_RE = re.compile(
    r"(?ms)^\*\*Raises:\*\*\n(?P<body>.*?)(?=\n\n|\n\*\*[A-Z][a-z]+:\*\*|\n#{1,6} |\Z)",
)
# Multi-line Google/mdxify items: "- `name`: desc" with continuation lines.
_ARG_ITEM_RE = re.compile(
    r"^- `([^`]+)`:\s*(.*?)(?=\n- `|\Z)",
    re.MULTILINE | re.DOTALL,
)
_RAISE_ITEM_RE = _ARG_ITEM_RE

# Sphinx cross-refs left in Google docstrings: :class:`~pkg.Name` → `Name`
_SPHINX_ROLE_RE = re.compile(
    r":(?:class|func|meth|attr|exc|data|mod|obj):`(?P<label>~?)(?P<target>[^`]+)`"
)
_ESCAPED_PUNCT_IN_CODE_RE = re.compile(r"`([^`]*\\[^`]+)`")


def _run_mdxify(tmpdir: Path, repo_url: str, branch: str, docstring_style: str) -> Path:
    """Invoke mdxify into a temporary directory; ensure root package page exists."""
    out = tmpdir / "raw"
    out.mkdir(parents=True, exist_ok=True)
    nav_tmp = tmpdir / "raw-nav.json"
    cmd = [
        sys.executable,
        "-m",
        "mdxify",
        "--all",
        "--root-module",
        PACKAGE,
        "--output-dir",
        str(out),
        "--nav-output",
        str(nav_tmp),
        "--repo-url",
        repo_url,
        "--branch",
        branch,
        "--docstring-style",
        docstring_style,
        "--format",
        "mdx",
    ]
    for prefix in EXCLUDE_PREFIXES:
        cmd.extend(["--exclude", prefix])

    env = os.environ.copy()
    env.setdefault("TZ", "UTC")
    env.setdefault("LC_ALL", "C.UTF-8")
    env.setdefault("SOURCE_DATE_EPOCH", "0")

    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, cwd=ROOT, env=env)
    _ensure_root_package_page(out, repo_url, branch, docstring_style)
    return out


def _ensure_root_package_page(
    raw_dir: Path, repo_url: str, branch: str, docstring_style: str
) -> None:
    """mdxify --all skips the root package; generate it explicitly from __init__.py."""
    target = raw_dir / f"{PACKAGE}-__init__.mdx"
    if target.exists():
        return
    from mdxify.discovery import get_module_source_file
    from mdxify.generator import generate_mdx
    from mdxify.parser import parse_module_fast

    source = get_module_source_file(PACKAGE)
    if source is None:
        raise SystemExit(f"could not locate source for {PACKAGE}")
    info = parse_module_fast(PACKAGE, source, include_internal=False)
    wrote = generate_mdx(
        info,
        target,
        repo_url=repo_url,
        branch=branch,
        root_module=PACKAGE,
        docstring_style=docstring_style,
        skip_empty=False,
    )
    if not wrote and not target.exists():
        raise SystemExit(f"failed to generate root package page for {PACKAGE}")
    print(f"added root package page → {target.name}")


def _stem_to_module(stem: str) -> str:
    if stem.endswith("-__init__"):
        return stem[: -len("-__init__")].replace("-", ".")
    return stem.replace("-", ".")


def _module_to_relpath(module: str) -> str:
    """Map a dotted module to a docs-relative path (no extension)."""
    if module == PACKAGE:
        return "api-reference"
    rest = module[len(PACKAGE) + 1 :]
    return "api/" + rest.replace(".", "-")


def _display_title(module: str) -> str:
    if module == PACKAGE:
        return "API reference"
    return module[len(PACKAGE) + 1 :]


def _sidebar_title(module: str) -> str:
    if module == PACKAGE:
        return "API reference"
    return module.rsplit(".", 1)[-1]


def _parse_frontmatter(text: str) -> tuple[dict[str, str], str]:
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    meta: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" in line:
            key, value = line.split(":", 1)
            meta[key.strip()] = value.strip().strip("\"'")
    return meta, text[match.end() :]


def _write_frontmatter(meta: dict[str, str], body: str) -> str:
    lines = ["---"]
    for key in ("title", "sidebarTitle", "description"):
        if key in meta and meta[key]:
            value = meta[key].replace('"', '\\"')
            lines.append(f'{key}: "{value}"')
    for key, value in meta.items():
        if key in {"title", "sidebarTitle", "description"}:
            continue
        value = value.replace('"', '\\"')
        lines.append(f'{key}: "{value}"')
    lines.append("---")
    lines.append("")
    return "\n".join(lines) + body.lstrip("\n")


def _fence_indented_blocks(prose: str) -> str:
    """Wrap contiguous 4-space-indented blocks in ```python fences."""

    def repl(match: re.Match[str]) -> str:
        block = match.group("body")
        # Skip if this looks like a markdown list continuation under Args.
        stripped_lines = [ln for ln in block.splitlines() if ln.strip()]
        if not stripped_lines:
            return block
        if all(re.match(r"\s*-\s", ln) for ln in stripped_lines):
            return block
        dedented = "\n".join(
            re.sub(r"^(?: {4}|\t)", "", ln) for ln in block.rstrip("\n").splitlines()
        )
        return f"```python\n{dedented}\n```\n\n"

    return _merge_adjacent_python_fences(_INDENTED_BLOCK_RE.sub(repl, prose))


_ADJACENT_PYTHON_FENCES_RE = re.compile(
    r"```python\n([\s\S]*?)\n```\n+(?=```python\n)",
)


def _merge_adjacent_python_fences(prose: str) -> str:
    """Collapse consecutive ```python fences (from split indented blocks) into one."""
    while True:
        merged, count = _ADJACENT_PYTHON_FENCES_RE.subn(r"```python\n\1\n\n", prose, count=1)
        if count == 0:
            return prose
        prose = merged


def _render_args(body: str) -> str:
    parts = ["**Parameters**", ""]
    for match in _ARG_ITEM_RE.finditer(body.strip() + "\n"):
        name, desc = match.group(1), " ".join(match.group(2).split())
        safe_name = name.replace('"', "&quot;")
        parts.append(f'<ParamField path="{safe_name}">')
        parts.append(f"  {desc}" if desc else "  ")
        parts.append("</ParamField>")
        parts.append("")
    if len(parts) == 2:
        # No list items — keep the section prose as-is under a heading.
        prose = body.strip()
        return f"**Parameters**\n\n{prose}\n" if prose else ""
    return "\n".join(parts).rstrip() + "\n"


def _render_returns(body: str) -> str:
    text = " ".join(body.strip().split())
    text = re.sub(r"^- ", "", text)
    parts = [
        "**Returns**",
        "",
        '<ResponseField name="returns">',
        f"  {text}",
        "</ResponseField>",
        "",
    ]
    return "\n".join(parts)


def _render_raises(body: str) -> str:
    parts = ["**Raises**", ""]
    for match in _RAISE_ITEM_RE.finditer(body.strip() + "\n"):
        name, desc = match.group(1), " ".join(match.group(2).split())
        safe_name = name.replace('"', "&quot;")
        parts.append(f'<ResponseField name="{safe_name}" type="exception">')
        parts.append(f"  {desc}" if desc else "  ")
        parts.append("</ResponseField>")
        parts.append("")
    if len(parts) == 2:
        prose = body.strip()
        return f"**Raises**\n\n{prose}\n" if prose else ""
    return "\n".join(parts).rstrip() + "\n"


def _normalize_sphinx_refs(text: str) -> str:
    def repl(match: re.Match[str]) -> str:
        target = match.group("target")
        label = target.rsplit(".", 1)[-1] if match.group("label") == "~" else target
        return f"`{label}`"

    return _SPHINX_ROLE_RE.sub(repl, text)


def _unescape_code_punct(text: str) -> str:
    """Undo mdxify escapes like ``http\\://…\\:9000`` inside inline code."""

    def repl(match: re.Match[str]) -> str:
        inner = match.group(1).replace("\\:", ":").replace("\\/", "/")
        return f"`{inner}`"

    return _ESCAPED_PUNCT_IN_CODE_RE.sub(repl, text)


def _enhance_sections(prose: str) -> str:
    prose = _ARGS_SECTION_RE.sub(lambda m: _render_args(m.group("body")), prose)
    prose = _RETURNS_SECTION_RE.sub(lambda m: _render_returns(m.group("body")), prose)
    prose = _RAISES_SECTION_RE.sub(lambda m: _render_raises(m.group("body")), prose)
    prose = re.sub(r"(?m)^\*\*Examples:\*\*\s*$", "**Examples**", prose)
    return prose


def _transform_prose(prose: str) -> str:
    prose = _normalize_sphinx_refs(prose)
    # Convert RST ``name`` → `name` only outside fenced code. Matching inside
    # ``` fences eats the middle pair of backticks and leaves broken ``python``.
    prose = _map_outside_fences(prose, lambda chunk: _RST_DOUBLE_TICK.sub(r"`\1`", chunk))
    prose = _map_outside_fences(prose, _unescape_code_punct)
    prose = _fence_indented_blocks(prose)
    prose = _enhance_sections(prose)
    prose = _PLACEHOLDER_URL.sub(lambda m: f"`{m.group(0)}`", prose)
    # Escape JSX braces outside fences / already-fenced content.
    return _map_outside_fences(prose, _escape_braces_outside_jsx)


def _map_outside_fences(prose: str, transform) -> str:
    """Apply ``transform`` to text outside ``` fenced regions."""
    parts: list[str] = []
    last = 0
    for match in _FENCE_PATTERN.finditer(prose):
        parts.append(transform(prose[last : match.start()]))
        parts.append(match.group(0))
        last = match.end()
    parts.append(transform(prose[last:]))
    return "".join(parts)


_JSX_TAG_RE = re.compile(r"</?(?:ParamField|ResponseField|Icon|sup|a)\b[^>]*>")


def _escape_braces_outside_jsx(text: str) -> str:
    """Escape `{`/`}` except inside known JSX tags."""
    parts: list[str] = []
    last = 0
    for match in _JSX_TAG_RE.finditer(text):
        parts.append(
            text[last : match.start()].replace("{", "&#123;").replace("}", "&#125;")
        )
        parts.append(match.group(0))
        last = match.end()
    parts.append(text[last:].replace("{", "&#123;").replace("}", "&#125;"))
    return "".join(parts)


def _finalize_page(module: str, raw_text: str) -> str:
    """Rewrite frontmatter + body for a single module page."""
    raw_text = SOURCE_MARKER_RE.sub("", raw_text)
    _meta, body = _parse_frontmatter(raw_text)
    body = _transform_prose(body)

    # Replace mdxify H1 (`# \`agentconnect.agent\``) with display title.
    title = _display_title(module)
    body = re.sub(
        r"(?m)^# `[^`]+`\s*$",
        f"# `{title if module != PACKAGE else PACKAGE}`",
        body,
        count=1,
    )
    if module == PACKAGE:
        # Prefer a human title for the API landing page.
        body = re.sub(r"(?m)^# `agentconnect`\s*$", "# API reference", body, count=1)

    meta = {
        "title": title if module != PACKAGE else "API reference",
        "sidebarTitle": _sidebar_title(module),
    }
    stamped_body = GENERATED_BANNER + body.lstrip("\n")
    return _write_frontmatter(meta, stamped_body)


def _collect_modules(raw_dir: Path) -> dict[str, Path]:
    mapping: dict[str, Path] = {}
    for path in sorted(raw_dir.glob("*.mdx")):
        module = _stem_to_module(path.stem)
        mapping[module] = path
    return mapping


def _has_children(module: str, modules: set[str]) -> bool:
    prefix = module + "."
    return any(m.startswith(prefix) for m in modules)


def _build_nav(modules: set[str]) -> list[Any]:
    """Build Mintlify nav: root page first, then short-named groups with roots."""

    # Tree under PACKAGE (exclude the root package itself from the tree).
    children = sorted(m for m in modules if m != PACKAGE and m.startswith(PACKAGE + "."))

    class Node:
        def __init__(self) -> None:
            self.module: str | None = None
            self.kids: dict[str, Node] = {}

    root = Node()
    root.module = PACKAGE if PACKAGE in modules else None

    for module in children:
        parts = module[len(PACKAGE) + 1 :].split(".")
        node = root
        for part in parts:
            node = node.kids.setdefault(part, Node())
        node.module = module

    def emit(name: str, node: Node, *, top: bool) -> Any:
        assert node.module is not None
        path = _module_to_relpath(node.module)
        if not node.kids:
            return path
        # Package with children: group label is short name; root is __init__ page.
        pages: list[Any] = []
        for child_name in sorted(node.kids):
            pages.append(emit(child_name, node.kids[child_name], top=False))
        label = name  # already short at every level
        return {"group": label, "root": path, "pages": pages}

    nav: list[Any] = []
    if root.module is not None:
        nav.append(_module_to_relpath(root.module))

    # Top-level entries under the package: groups or leaves, short labels.
    top_items: list[Any] = []
    for name in sorted(root.kids):
        top_items.append(emit(name, root.kids[name], top=True))

    # Leaves (cli, mcp) before groups for stable scanning — match prior mdxify feel.
    def sort_key(item: Any) -> tuple[int, str]:
        if isinstance(item, dict):
            return (1, item["group"])
        return (0, str(item))

    top_items.sort(key=sort_key)
    nav.extend(top_items)
    return nav


def _reshape(raw_dir: Path) -> list[str]:
    """Write final api pages + nav; return list of generated relative paths."""
    modules = _collect_modules(raw_dir)
    if PACKAGE not in modules:
        raise SystemExit(f"mdxify did not produce a page for {PACKAGE}")

    # Wipe previous generated outputs.
    if API_DIR.exists():
        shutil.rmtree(API_DIR)
    API_DIR.mkdir(parents=True, exist_ok=True)
    if ROOT_PAGE.exists():
        ROOT_PAGE.unlink()
    # Remove legacy python-api tree if present from earlier revisions.
    legacy = DOCS / "python-api"
    if legacy.exists():
        shutil.rmtree(legacy)
    legacy_nav = DOCS / "python-api-pages.json"
    if legacy_nav.exists():
        legacy_nav.unlink()

    written: list[str] = []
    for module, src in sorted(modules.items()):
        rel = _module_to_relpath(module)
        dest = DOCS / f"{rel}.mdx"
        dest.parent.mkdir(parents=True, exist_ok=True)
        text = _finalize_page(module, src.read_text(encoding="utf-8"))
        dest.write_text(text, encoding="utf-8")
        written.append(rel)

    nav = _build_nav(set(modules))
    NAV_FILE.write_text(json.dumps(nav, indent=2) + "\n", encoding="utf-8")
    return written


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-url",
        default="https://github.com/AKKI0511/AgentConnect",
    )
    parser.add_argument(
        "--branch",
        default="team-restructure",
        help="Git branch used for source links",
    )
    parser.add_argument(
        "--docstring-style",
        default="google",
        choices=("google", "numpy", "sphinx"),
    )
    args = parser.parse_args(argv)

    with tempfile.TemporaryDirectory(prefix="ac-mdxify-") as tmp:
        tmpdir = Path(tmp)
        raw_dir = _run_mdxify(tmpdir, args.repo_url, args.branch, args.docstring_style)
        written = _reshape(raw_dir)

    print(f"Generated {len(written)} API pages → {API_DIR.relative_to(ROOT)}/ + api-reference.mdx")
    print(f"Navigation → {NAV_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
