"""BaseAgent: subclass, give a Profile, implement ``process_message``.

Join a running Team in-process or by URL. The Session pulls work, maps
handler outcomes onto Runtime ``reply`` / ``complete``, and reconnects
when the Team comes back.

    class Researcher(BaseAgent):
        async def process_message(self, msg, ctx):
            return f"noted: {msg['content']}"

    team = await Team("content-squad").start()
    await Researcher(name="researcher").join(team)

The same class joins a Team in another process with
``await Researcher(name="researcher").join("http://127.0.0.1:9000")``.

Handler outcomes:

- return a JSON value to reply to a reply-expected request
- return None to decline that request, or to finish an event
- raise to fail the request (the requester sees ``handler_failed``)
- call ``ctx.ticket()`` and answer later through the returned handle

Several running copies of one Agent share one Mailbox. Conversation
state belongs to the Thread (``ctx.history``), not to this process.
"""

from __future__ import annotations

import logging
import re
import time
import uuid
from pathlib import Path
from typing import TYPE_CHECKING, Any, List, Mapping, Optional, Union, cast

from dotenv import load_dotenv

from agentconnect.agent.errors import SessionError
from agentconnect.agent.session import Session
from agentconnect.core.address import parse_agent_name
from agentconnect.core.exceptions import SecurityError
from agentconnect.core.identity import AgentIdentity, VerificationStatus
from agentconnect.core.kinds import MessageKind
from agentconnect.core.profile import AgentProfile
from agentconnect.core.types import InteractionMode
from agentconnect.utils import wallet_manager

if TYPE_CHECKING:
    from coinbase_agentkit import AgentKit as _AgentKit
    from coinbase_agentkit import CdpWalletProvider as _CdpWalletProvider

logger = logging.getLogger(__name__)

_DID_KEY = re.compile(r"^did:key:z[1-9A-HJ-NP-Za-km-z]+$")
_B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
_SKILL_NAME = re.compile(r"^[a-z0-9](?:[a-z0-9_-]{0,61}[a-z0-9])?$")


class BaseAgent:
    """Client that joins a Team, pulls Deliveries, and runs a handler.

    ``name`` is unique within the Team. ``instance_id`` identifies this
    running copy. The SDK generates one unless you pass a stable value;
    two copies must not share an ``instance_id``.
    """

    profile: Any = None

    def __init__(
        self,
        name: Optional[str] = None,
        *,
        profile: Any = None,
        identity: Optional[AgentIdentity] = None,
        instance_id: Optional[str] = None,
        max_in_flight: int = 1,
        agent_id: Optional[str] = None,
        interaction_modes: Optional[List[InteractionMode]] = None,
        enable_payments: bool = False,
        wallet_data_dir: Optional[Union[str, Path]] = None,
        **kwargs: Any,
    ) -> None:
        """Create an Agent that has not yet joined a Team.

        Args:
            name: Agent name, unique within the Team. ``agent_id`` is an alias.
            profile: Discovery Profile (mapping or ``AgentProfile``). A class
                attribute named ``profile`` is used when this is omitted.
            identity: Optional keypair. A valid ``did:key`` on it is reused;
                otherwise the SDK mints one for join.
            instance_id: Stable id for this running copy. Generated by default.
            max_in_flight: How many Deliveries this Session handles at once.
        """
        del kwargs
        raw_name = name or agent_id
        if not raw_name:
            raise ValueError("name is required")
        canonical = parse_agent_name(raw_name)
        if canonical is None:
            raise ValueError("name is not a valid Agent name")
        self._agent_name = canonical
        self.name = canonical
        self.agent_id = canonical
        self.identity = identity or AgentIdentity.create_key_based()
        self.agent_did = _runtime_did(self.identity)
        self.profile = profile if profile is not None else type(self).profile
        self.interaction_modes = interaction_modes or []
        if self.profile is not None and hasattr(self.profile, "capabilities"):
            self.capabilities = self.profile.capabilities
        else:
            self.capabilities = []
        if instance_id is None:
            self.instance_id = str(uuid.uuid4())
        else:
            try:
                self.instance_id = str(uuid.UUID(str(instance_id)))
            except ValueError as exc:
                raise ValueError("instance_id must be a UUID") from exc
        try:
            in_flight = int(max_in_flight)
        except (TypeError, ValueError) as exc:
            raise ValueError("max_in_flight must be an integer") from exc
        if in_flight < 1 or in_flight > 100:
            raise ValueError("max_in_flight must be between 1 and 100")
        self.max_in_flight = in_flight
        self._session: Optional[Session] = None
        self._session_ttl_hint = 300.0
        self.hub = None
        self.registry = None
        self.active_conversations: dict[str, Any] = {}
        self.cooldown_until = 0.0
        self.pending_requests: dict[str, Any] = {}
        self._verified_logged_once = False
        self.enable_payments = enable_payments
        self.wallet_provider: Optional[_CdpWalletProvider] = None
        self.agent_kit: Optional[_AgentKit] = None
        if enable_payments:
            self._init_payments(wallet_data_dir)

    @property
    def address(self) -> Optional[str]:
        """Qualified Address after join, otherwise None."""
        if self._session is None:
            return None
        return self._session.address

    @property
    def connected(self) -> bool:
        """True while this copy holds a live Session."""
        return self._session is not None and self._session.connected

    @property
    def is_running(self) -> bool:
        """True while the Session supervisor is running."""
        return self._session is not None and not self._session._stopped

    @property
    def payments_enabled(self) -> bool:
        """True when payment capabilities initialized successfully."""
        return self.enable_payments and self.wallet_provider is not None

    async def join(self, team_or_url: Any) -> "BaseAgent":
        """Join a Team. Pass a started Team, or a URL this Team is serving.

        Retries while the Team is not up yet. After a disconnect, the
        Session reconnects on its own with the same ``instance_id``.
        """
        if self._session is not None:
            await self.leave()
        session = Session(
            self,
            team_or_url,
            instance_id=self.instance_id,
            agent_did=self.agent_did,
            profile=_discovery_profile(self.profile, self._agent_name),
            max_in_flight=self.max_in_flight,
        )
        self._session = session
        await session.start()
        return self

    async def leave(self) -> None:
        """Disconnect this Session. Membership, Mailbox, and Tickets remain."""
        session = self._session
        self._session = None
        if session is not None:
            await session.close(disconnect=True)

    async def stop(self) -> None:
        """Disconnect and drop local payment handles. Same as ``leave`` for the Session."""
        await self.leave()
        self.wallet_provider = None
        self.agent_kit = None
        self.reset_cooldown()
        self.pending_requests.clear()

    async def ask(
        self,
        recipient: str,
        content: Any,
        *,
        deadline_seconds: float = 30.0,
        collect: str = "wait",
        thread_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        metadata: Optional[Mapping[str, Any]] = None,
    ) -> dict[str, Any]:
        """Send a reply-expected request through this Session."""
        return await self._require_session().ask(
            recipient,
            content,
            deadline_seconds=deadline_seconds,
            collect=collect,
            thread_id=thread_id,
            parent_id=parent_id,
            metadata=metadata,
        )

    async def tell(
        self,
        recipient: str,
        content: Any,
        *,
        kind: str = "event",
        thread_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        metadata: Optional[Mapping[str, Any]] = None,
    ) -> dict[str, Any]:
        """Send an event or a no-reply request through this Session."""
        return await self._require_session().tell(
            recipient,
            content,
            kind=kind,
            thread_id=thread_id,
            parent_id=parent_id,
            metadata=metadata,
        )

    async def find(
        self, query: str, *, limit: int = 10, detail: str = "summary"
    ) -> dict[str, Any]:
        """Search this Team's Directory, excluding this Agent."""
        return await self._require_session().find(query, limit=limit, detail=detail)

    async def get_profile(self, address: str) -> dict[str, Any]:
        """Return the Directory entry for ``address``."""
        return await self._require_session().get_profile(address)

    async def get_result(self, ticket_id: str) -> dict[str, Any]:
        """Return a Ticket this Agent opened."""
        return await self._require_session().get_result(ticket_id)

    async def process_message(self, message: Mapping[str, Any], ctx: Any = None) -> Any:
        """Handle one Delivery.

        Override this. ``message`` is the Runtime Message mapping
        (``id``, ``sender``, ``recipient``, ``kind``, ``content``, ...).
        ``ctx`` is a :class:`~agentconnect.agent.context.Context`.

        Return a value to reply, return None to decline or finish, raise
        to fail, or call ``ctx.ticket()`` and answer later.
        """
        return None

    async def send_message(
        self,
        receiver_id: str,
        content: Any,
        kind: MessageKind = MessageKind.EVENT,
        metadata: Optional[dict] = None,
    ) -> dict[str, Any]:
        """Send through the Session. Prefer ``ask`` / ``tell`` in new code."""
        if kind == MessageKind.REQUEST:
            return await self.ask(receiver_id, content, metadata=metadata)
        if kind == MessageKind.EVENT:
            return await self.tell(
                receiver_id, content, kind="event", metadata=metadata
            )
        raise ValueError("send_message only sends request or event")

    def _require_session(self) -> Session:
        if self._session is None or not self._session.session_token:
            raise SessionError("unauthorized", "Agent has not joined a Team")
        return self._session

    async def verify_identity(self) -> bool:
        """Verify this Agent's DID. Join stamps identity at the Runtime."""
        if self.identity.verification_status == VerificationStatus.VERIFIED:
            return True
        try:
            if self.identity.did.startswith("did:ethr:"):
                verified = await self._verify_ethereum_did()
            elif self.identity.did.startswith("did:key:"):
                verified = await self._verify_key_did()
            else:
                raise ValueError("Unsupported DID method")
            self.identity.verification_status = (
                VerificationStatus.VERIFIED if verified else VerificationStatus.FAILED
            )
            if verified and not self._verified_logged_once:
                logger.info("Identity verified agent_id=%s", self.agent_id)
                self._verified_logged_once = True
            return verified
        except Exception:
            self.identity.verification_status = VerificationStatus.FAILED
            raise SecurityError("Identity verification failed")

    async def _verify_ethereum_did(self) -> bool:
        return True

    async def _verify_key_did(self) -> bool:
        return True

    def set_cooldown(self, duration: int) -> None:
        """Block sending and receiving for ``duration`` seconds."""
        self.cooldown_until = time.time() + duration

    def is_in_cooldown(self) -> bool:
        """Return True while a cooldown is active."""
        return time.time() < self.cooldown_until

    def reset_cooldown(self) -> None:
        """Clear any cooldown."""
        self.cooldown_until = 0.0

    def end_conversation(self, other_agent_id: str) -> None:
        """Drop local conversation bookkeeping with ``other_agent_id``."""
        self.active_conversations.pop(other_agent_id, None)

    async def can_send_message(self, receiver_id: str) -> bool:
        """Return False during cooldown. Opens local conversation bookkeeping."""
        if self.is_in_cooldown():
            return False
        if receiver_id not in self.active_conversations:
            self.active_conversations[receiver_id] = {
                "start_time": time.time(),
                "message_count": 0,
            }
        return True

    async def can_receive_message(self, sender_id: str) -> bool:
        """Return False during cooldown."""
        return not self.is_in_cooldown()

    def mint_mcp_access_token(self, audience: str, ttl_s: int = 600) -> str:
        """Mint an RS256 JWT for Authorization: Bearer against an MCP server."""
        if not self.identity or not getattr(self.identity, "private_key", None):
            raise ValueError("Agent identity has no private key for signing")
        now = int(time.time())
        claims: dict[str, object] = {
            "sub": self.agent_id,
            "aud": audience,
            "iat": now,
            "exp": now + int(ttl_s),
            "jti": str(uuid.uuid4()),
        }
        try:
            from jose import jwt
        except Exception as exc:
            raise RuntimeError("python-jose is required to mint JWTs") from exc
        private_key_pem: str = self.identity.private_key
        headers = {"alg": "RS256", "kid": f"agent:{self.agent_id}"}
        return jwt.encode(claims, private_key_pem, algorithm="RS256", headers=headers)

    def _init_payments(self, wallet_data_dir: Optional[Union[str, Path]]) -> None:
        try:
            load_dotenv()
            wallet_data = wallet_manager.load_wallet_data(
                self.agent_id, wallet_data_dir
            )
            from coinbase_agentkit import (
                AgentKit,
                AgentKitConfig,
                CdpWalletProvider,
                CdpWalletProviderConfig,
                wallet_action_provider,
                erc20_action_provider,
                cdp_api_action_provider,
            )
            from agentconnect.config import settings as global_settings

            cdp_config = (
                CdpWalletProviderConfig(wallet_data=wallet_data)
                if wallet_data
                else None
            )
            self.wallet_provider = cast(
                "_CdpWalletProvider", CdpWalletProvider(cdp_config)
            )
            action_providers = [wallet_action_provider(), cdp_api_action_provider()]
            payment_symbol = global_settings.payments.default_token_symbol
            if payment_symbol != "ETH":
                action_providers.append(erc20_action_provider())
            self.agent_kit = cast(
                "_AgentKit",
                AgentKit(
                    AgentKitConfig(
                        wallet_provider=self.wallet_provider,
                        action_providers=action_providers,
                    )
                ),
            )
            if not wallet_data:
                try:
                    new_wallet_data = self.wallet_provider.export_wallet()
                    wallet_manager.save_wallet_data(
                        self.agent_id, new_wallet_data, wallet_data_dir
                    )
                except Exception as exc:
                    logger.warning(
                        "Failed to persist new wallet data agent_id=%s: %s",
                        self.agent_id,
                        exc,
                    )
            try:
                wallet_address = self.wallet_provider.get_address()
                if wallet_address and self.profile is not None:
                    try:
                        self.profile.payment_address = wallet_address
                    except Exception:
                        pass
            except Exception as exc:
                logger.error(
                    "Error retrieving wallet address agent_id=%s: %s",
                    self.agent_id,
                    exc,
                )
        except Exception as exc:
            logger.error(
                "Error initializing payment capabilities agent_id=%s: %s",
                self.agent_id,
                exc,
            )
            self.wallet_provider = None
            self.agent_kit = None


def _runtime_did(identity: AgentIdentity) -> str:
    """Return a Runtime-acceptable did:key, minting one when identity.did is not."""
    if identity.did and _DID_KEY.fullmatch(identity.did):
        return identity.did
    raw = uuid.uuid4().bytes + uuid.uuid4().bytes
    body = "".join(_B58[byte % len(_B58)] for byte in raw)[:48]
    return "did:key:z" + body


def _skill_name(value: str, fallback: str) -> str:
    lowered = re.sub(r"[^a-z0-9_-]+", "-", value.strip().lower()).strip("-_")
    if _SKILL_NAME.fullmatch(lowered):
        return lowered
    return fallback


def _discovery_profile(profile: Any, name: str) -> dict[str, Any]:
    """Build the discovery Profile the Runtime accepts on join."""
    if isinstance(profile, Mapping) and "summary" in profile and "skills" in profile:
        out = {
            "summary": profile["summary"],
            "skills": list(profile["skills"]),
        }
        if profile.get("description"):
            out["description"] = profile["description"]
        if profile.get("tags"):
            out["tags"] = list(profile["tags"])
        return out
    if isinstance(profile, AgentProfile):
        summary = (
            profile.summary
            or profile.description
            or f"{name} handles work for this team."
        )
        skills: list[dict[str, str]] = []
        seen: set[str] = set()
        for skill in profile.skills or []:
            skill_name = _skill_name(skill.name, "generic")
            if skill_name in seen:
                continue
            seen.add(skill_name)
            desc = skill.description or skill.name
            skills.append({"name": skill_name, "description": desc})
        for cap in profile.capabilities or []:
            skill_name = _skill_name(getattr(cap, "name", ""), "generic")
            if skill_name in seen:
                continue
            seen.add(skill_name)
            desc = getattr(cap, "description", None) or skill_name
            skills.append({"name": skill_name, "description": desc})
        if not skills:
            skills = [
                {
                    "name": "generic",
                    "description": f"Work handled by {name}.",
                }
            ]
        out = {"summary": str(summary)[:200], "skills": skills}
        if profile.tags:
            out["tags"] = list(profile.tags)
        return out
    return {
        "summary": f"{name} handles work for this team.",
        "skills": [{"name": "generic", "description": f"Work handled by {name}."}],
    }
