"""BaseAgent: subclass, give a Profile, implement ``handle``.

Join a running Team in-process or by URL. The Session pulls work, maps
handler outcomes onto Runtime ``reply`` / ``complete``, and reconnects
when the Team comes back.

    from agentconnect import AgentProfile, BaseAgent, Context, MailboxMessage, Skill
    from agentconnect.team import Team

    class Researcher(BaseAgent):
        profile = AgentProfile(
            summary="Finds sources and asks a writer to draft.",
            skills=[
                Skill(
                    name="research",
                    description="Turn a question into notes a writer can use.",
                )
            ],
        )

        async def handle(self, msg: MailboxMessage, ctx: Context) -> str | None:
            if msg.kind != "request":
                return None
            return f"noted: {msg.content}"

    team = await Team("content-squad").start()
    await Researcher(name="researcher").join(team)

    The same class joins a Team in another process with a join token.
    Pass ``identity_path`` so a restart keeps the same DID:

        issued = await team.issue_join_token(name="researcher", agent_did=agent.agent_did)
        await Researcher(name="researcher", identity_path="researcher.json").join(
            url, join_token=issued["token"]
        )

Handler outcomes:

- return a JSON value to reply to a request
- return None to decline that request, or to finish an event
- raise to fail the request. The requester sees ``handler_failed`` with
  the generic text ``The handler failed.`` Diagnostics stay in this
  process log. Pass a specific message with ``ctx.defer().fail(...)``.
- call ``ctx.defer()`` and answer later through the returned handle.
  The Session renews that Delivery lease until the reply, the request
  deadline, disconnect, or revocation. The slot still counts toward
  ``max_in_flight``.

Several running copies of one Agent share one Mailbox. Conversation
state belongs to the Thread (``ctx.history``), not to this process.
"""

from __future__ import annotations

import logging
import os
import uuid
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Optional

from agentconnect.agent.context import Context
from agentconnect.agent.errors import SessionError
from agentconnect.agent.identity import load_or_create_identity
from agentconnect.agent.session import Session
from agentconnect.agent.tools import TeamTools
from agentconnect.core.address import parse_agent_name
from agentconnect.core.base import JsonValue
from agentconnect.core.directory import DirectoryEntry, FindResult
from agentconnect.core.identity import AgentIdentity
from agentconnect.core.message import MailboxMessage
from agentconnect.core.operations import AcceptedSendResult, HistoryResult
from agentconnect.core.primitives import CollectMode, DeliveryHistoryForm
from agentconnect.core.profile import AgentProfile
from agentconnect.core.ticket import Ticket

logger = logging.getLogger(__name__)

_ProfileArg = AgentProfile | Mapping[str, Any] | None


class BaseAgent:
    """Client that joins a Team, pulls Deliveries, and runs a handler.

    ``name`` is unique within the Team. ``instance_id`` identifies this
    running copy. The SDK generates one unless you pass a stable value;
    two copies must not share an ``instance_id``. Pass ``identity_path``
    to persist the Agent key across process restarts.
    """

    profile: AgentProfile
    _session_ttl_hint: float

    def __init__(
        self,
        name: str,
        *,
        profile: _ProfileArg = None,
        identity: Optional[AgentIdentity] = None,
        identity_path: Optional[str | Path] = None,
        instance_id: Optional[str] = None,
        max_in_flight: int = 1,
        delivery_history: DeliveryHistoryForm = "bodies",
        join_token: Optional[str] = None,
    ) -> None:
        """Create an Agent that has not yet joined a Team.

        Args:
            name: Agent name, unique within the Team.
            profile: Discovery :class:`~agentconnect.core.profile.AgentProfile`
                or a mapping with the same fields. A class attribute named
                ``profile`` is used when this is omitted.
            identity: Optional keypair. A valid ``did:key`` on it is reused;
                otherwise the SDK mints one for join. Do not pass this
                together with ``identity_path``. Callers that persist the
                key themselves can load it with
                :func:`~agentconnect.agent.identity.load_identity` and pass
                the result here.
            identity_path: JSON file for the Agent key. Loaded when it
                exists, otherwise created. Restarting with the same path
                keeps the same DID.

                agent = Researcher(name="researcher", identity_path="researcher.json")
            instance_id: Stable id for this running copy. Generated by default.
            max_in_flight: How many Deliveries this Session handles at once,
                including deferred replies that still hold a lease.
            delivery_history: ``"bodies"`` (default) puts earlier Messages on
                each Delivery. ``"ids"`` puts only their ids; page bodies
                with ``get_history``.
            join_token: Token issued by the Team. Required when joining a
                Team that has ``require_join_auth=True``. Also read from
                ``AGENTCONNECT_JOIN_TOKEN``.
        """
        canonical = parse_agent_name(name)
        if canonical is None:
            raise ValueError("name is not a valid Agent name")
        self._agent_name = canonical
        self.name = canonical
        if identity is not None and identity_path is not None:
            raise ValueError("pass identity or identity_path, not both")
        if identity_path is not None:
            self.identity = load_or_create_identity(identity_path)
        else:
            self.identity = identity or AgentIdentity.create_key_based()
        try:
            if not self.identity.matches_did():
                from agentconnect.core.identity import did_key_from_public_bytes

                self.identity.did = did_key_from_public_bytes(
                    self.identity.public_bytes()
                )
        except Exception as exc:
            raise ValueError("identity must be an Ed25519 did:key") from exc
        self.agent_did = self.identity.did
        env_token = os.environ.get("AGENTCONNECT_JOIN_TOKEN")
        self.join_token = join_token if join_token is not None else env_token
        self.profile = _discovery_profile(
            profile if profile is not None else _class_profile(type(self)),
            self._agent_name,
        )
        if instance_id is None:
            self.instance_id = str(uuid.uuid4())
        else:
            try:
                self.instance_id = str(uuid.UUID(str(instance_id)))
            except ValueError as exc:
                raise ValueError("instance_id must be a UUID") from exc
        try:
            in_flight = int(max_in_flight)
        except (TypeError, ValueError) as exc:
            raise ValueError("max_in_flight must be an integer") from exc
        if in_flight < 1 or in_flight > 100:
            raise ValueError("max_in_flight must be between 1 and 100")
        self.max_in_flight = in_flight
        if delivery_history not in {"bodies", "ids"}:
            raise ValueError("delivery_history must be 'bodies' or 'ids'")
        self.delivery_history = delivery_history
        self._session: Optional[Session] = None
        self._session_ttl_hint = 300.0

    @property
    def address(self) -> Optional[str]:
        """Qualified Address after join, otherwise None."""
        if self._session is None:
            return None
        return self._session.address

    @property
    def connected(self) -> bool:
        """True while this copy holds a live Session."""
        return self._session is not None and self._session.connected

    async def join(
        self, team_or_url: Any, *, join_token: Optional[str] = None
    ) -> "BaseAgent":
        """Join a Team. Pass a started Team, or a URL this Team is serving.

        Retries while the Team is not up yet. After a disconnect, the
        Session reconnects on its own with the same ``instance_id``.

        Args:
            team_or_url: A started ``Team``, or a Runtime origin such as
                ``http://127.0.0.1:9000``.
            join_token: Overrides the constructor / environment token for
                this join.
        """
        if join_token is not None:
            self.join_token = join_token
        if self._session is not None:
            await self.leave()
        session = Session(
            self,
            team_or_url,
            instance_id=self.instance_id,
            agent_did=self.agent_did,
            profile=self.profile.to_public_dict(),
            max_in_flight=self.max_in_flight,
            delivery_history=self.delivery_history,
        )
        self._session = session
        await session.start()
        return self

    async def leave(self) -> None:
        """Disconnect this Session. Membership, Mailbox, and Tickets remain."""
        session = self._session
        self._session = None
        if session is not None:
            await session.close(disconnect=True)

    async def ask(
        self,
        recipient: str,
        content: Any,
        *,
        deadline_seconds: Optional[float] = None,
        collect: CollectMode = "wait",
        thread_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        metadata: Optional[Mapping[str, Any]] = None,
    ) -> Ticket:
        """Send a reply-expected request through this Session.

        ``collect="wait"`` (default) holds until the Ticket is terminal or
        the Runtime wait hold elapses, then returns the current Ticket.
        That Ticket may still be ``open``. Ending the wait does not end
        accepted work. Read a completed reply as ``ticket.response.content``
        after checking ``ticket.state``. Collect later with ``get_result``.
        Omit ``deadline_seconds`` to inherit a request parent or use the
        Runtime work lifetime.

            ticket = await agent.ask("writer", {"task": "draft this"})
            if ticket.state == "completed":
                print(ticket.response.content)

            pending = await agent.ask("writer", "long job", collect="ticket")
            ticket = await agent.get_result(pending.id)

            thread_id = str(uuid.uuid4())
            await agent.ask("writer", "outline this", thread_id=thread_id)
            await agent.ask("writer", "expand section 2", thread_id=thread_id)
        """
        return await self._require_session().ask(
            recipient,
            content,
            deadline_seconds=deadline_seconds,
            collect=collect,
            thread_id=thread_id,
            parent_id=parent_id,
            metadata=metadata,
        )

    async def tell(
        self,
        recipient: str,
        content: Any,
        *,
        thread_id: Optional[str] = None,
        parent_id: Optional[str] = None,
        metadata: Optional[Mapping[str, Any]] = None,
    ) -> AcceptedSendResult:
        """Send an event through this Session. No Ticket is created.

        await agent.tell("writer", {"note": "source changed"})
        """
        return await self._require_session().tell(
            recipient,
            content,
            thread_id=thread_id,
            parent_id=parent_id,
            metadata=metadata,
        )

    async def find(
        self, query: str, *, limit: int | None = None, detail: str = "summary"
    ) -> FindResult:
        """Search this Team's Directory, excluding this Agent.

        found = await agent.find("someone who can draft a summary")
        found.matches[0].address
        """
        return await self._require_session().find(query, limit=limit, detail=detail)

    async def get_entry(self, address: str) -> DirectoryEntry:
        """Return the Directory entry for ``address``.

        The entry includes Address, DID, and Profile.

            entry = await agent.get_entry("writer")
            entry.profile.summary
        """
        return await self._require_session().get_entry(address)

    async def get_result(self, ticket_id: str) -> Ticket:
        """Return a Ticket this Membership opened.

        ticket = await agent.get_result(pending.id)
        """
        return await self._require_session().get_result(ticket_id)

    async def get_history(
        self,
        thread_id: str,
        *,
        before: Optional[str] = None,
        limit: int = 50,
    ) -> HistoryResult:
        """Return one page of retained Thread history.

        Omit ``before`` for the newest page. A UUID that is not in the
        transcript, including one retention has removed, returns that
        newest page.

            page = await agent.get_history(thread_id)
            if page.has_more:
                older = await agent.get_history(
                    thread_id, before=page.messages[0].id
                )
        """
        return await self._require_session().get_history(
            thread_id, before=before, limit=limit
        )

    def team_tools(self) -> TeamTools:
        """Return find, ask, tell, get_result, and get_history for this Agent.

        Safe to call before ``join``. The callables fail until a Session
        exists. Use these when the host does not speak MCP. Results are
        JSON via :func:`~agentconnect.core.base.dump_public`.

            tools = self.team_tools()
            found = await tools.find(query="someone who can draft a summary")
            ticket = await tools.ask(
                recipient=found["matches"][0]["address"],
                content=msg.content,
            )
            if ticket["state"] == "completed":
                return ticket["response"]["content"]
        """
        return TeamTools(self._require_session)

    async def handle(self, message: MailboxMessage, ctx: Context) -> JsonValue | None:
        """Handle one Delivery.

        Override this. ``message`` is the delivered request or event.
        ``ctx`` is always a :class:`~agentconnect.agent.context.Context`.

        Return a value to reply, return None to decline or finish, raise
        to fail, or call ``ctx.defer()`` and answer later.
        """
        return None

    def _require_session(self) -> Session:
        if self._session is None or not self._session.session_token:
            raise SessionError("unauthorized", "Agent has not joined a Team")
        return self._session


def _class_profile(cls: type) -> _ProfileArg:
    """Return a Profile declared on the Agent class, if any."""
    for klass in cls.__mro__:
        if "profile" not in klass.__dict__:
            continue
        value = klass.__dict__["profile"]
        if isinstance(value, (AgentProfile, Mapping)):
            return value
    return None


def _discovery_profile(profile: _ProfileArg, name: str) -> AgentProfile:
    """Return the discovery Profile the Runtime accepts on join."""
    fallback = {
        "summary": f"{name} handles work for this team.",
        "skills": [{"name": "generic", "description": f"Work handled by {name}."}],
    }
    if profile is None:
        return AgentProfile.model_validate(fallback)
    if isinstance(profile, AgentProfile):
        return profile
    return AgentProfile.model_validate(profile)
