#!/usr/bin/env python3
"""Validate the Mintlify website and generated Python API reference.

Checks:
  - docs.json parses and matches Mintlify's required shape
  - generated API reference is up to date (stale detection)
  - generation is deterministic (two consecutive runs match)
  - generated MDX files carry the do-not-edit banner
  - Mintlify build validation and broken-link detection
"""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

WEBSITE = Path(__file__).resolve().parents[1]
ROOT = WEBSITE.parent
API_DIR = WEBSITE / "python-api"
NAV_FILE = WEBSITE / "python-api-pages.json"
DOCS_JSON = WEBSITE / "docs.json"
GENERATE = WEBSITE / "scripts" / "generate_api.py"
HANDWRITTEN_INDEX = API_DIR / "index.mdx"
BANNER_NEEDLE = "DO NOT EDIT. Generated by"


def _fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    raise SystemExit(1)


def check_docs_json() -> None:
    """Invalid configuration: required Mintlify fields must be present."""
    try:
        data = json.loads(DOCS_JSON.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        _fail(f"docs.json is not valid JSON: {exc}")

    for key in ("name", "theme", "colors", "navigation"):
        if key not in data:
            _fail(f"docs.json missing required field: {key}")
    if "primary" not in data.get("colors", {}):
        _fail("docs.json colors.primary is required")
    if not isinstance(data["navigation"], dict) or not data["navigation"]:
        _fail("docs.json navigation must be a non-empty object")
    print("ok: docs.json configuration")


def _generated_mdx_paths() -> list[Path]:
    return sorted(
        p
        for p in API_DIR.rglob("*.mdx")
        if p.resolve() != HANDWRITTEN_INDEX.resolve()
    )


def check_generated_banners() -> None:
    """Accidental manual edits: every generated MDX must keep the banner."""
    paths = _generated_mdx_paths()
    if not paths:
        _fail("no generated API MDX files found; run make website-api")
    missing = [
        p.relative_to(WEBSITE).as_posix()
        for p in paths
        if BANNER_NEEDLE not in p.read_text(encoding="utf-8")
    ]
    if missing:
        sample = ", ".join(missing[:8])
        suffix = "…" if len(missing) > 8 else ""
        _fail(
            "generated API files missing do-not-edit banner "
            f"(re-run make website-api): {sample}{suffix}"
        )
    print(f"ok: generated banners ({len(paths)} mdx files)")


def _snapshot(dest: Path) -> None:
    """Copy generated outputs (excluding handwritten index) into dest."""
    dest.mkdir(parents=True, exist_ok=True)
    if not NAV_FILE.exists():
        _fail(f"missing {NAV_FILE.relative_to(ROOT)}; run make website-api")
    shutil.copy2(NAV_FILE, dest / "python-api-pages.json")
    api_dest = dest / "python-api"
    if api_dest.exists():
        shutil.rmtree(api_dest)
    shutil.copytree(
        API_DIR,
        api_dest,
        ignore=shutil.ignore_patterns("index.mdx"),
    )


def _trees_equal(left: Path, right: Path) -> list[str]:
    """Return relative paths that differ between two snapshots."""
    diffs: list[str] = []
    left_files = {
        p.relative_to(left).as_posix() for p in left.rglob("*") if p.is_file()
    }
    right_files = {
        p.relative_to(right).as_posix() for p in right.rglob("*") if p.is_file()
    }
    for rel in sorted(left_files | right_files):
        if rel not in left_files:
            diffs.append(f"only in regenerated: {rel}")
            continue
        if rel not in right_files:
            diffs.append(f"only in committed: {rel}")
            continue
        if not filecmp.cmp(left / rel, right / rel, shallow=False):
            diffs.append(f"content differs: {rel}")
    return diffs


def _restore_snapshot(snapshot: Path, index_text: str | None) -> None:
    """Replace generated outputs with a snapshot and restore handwritten index."""
    if API_DIR.exists():
        shutil.rmtree(API_DIR)
    shutil.copytree(snapshot / "python-api", API_DIR)
    shutil.copy2(snapshot / "python-api-pages.json", NAV_FILE)
    if index_text is not None:
        HANDWRITTEN_INDEX.write_text(index_text, encoding="utf-8")


def check_stale_and_deterministic(*, skip_deterministic: bool) -> None:
    """Regenerate and compare against the current tree; optionally twice."""
    if not API_DIR.exists() or not NAV_FILE.exists():
        _fail("generated API reference missing; run make website-api")

    index_text = (
        HANDWRITTEN_INDEX.read_text(encoding="utf-8")
        if HANDWRITTEN_INDEX.exists()
        else None
    )

    with tempfile.TemporaryDirectory(prefix="ac-website-") as tmp:
        tmp_path = Path(tmp)
        before = tmp_path / "before"
        after1 = tmp_path / "after1"
        after2 = tmp_path / "after2"
        _snapshot(before)

        try:
            subprocess.run([sys.executable, str(GENERATE)], check=True, cwd=ROOT)
            _snapshot(after1)

            if not skip_deterministic:
                subprocess.run([sys.executable, str(GENERATE)], check=True, cwd=ROOT)
                _snapshot(after2)
        finally:
            _restore_snapshot(before, index_text)

        stale = _trees_equal(before, after1)
        if stale:
            _fail(
                "generated API reference is stale; run `make website-api` and commit.\n"
                + "\n".join(stale[:20])
            )
        print("ok: generated API reference is up to date")

        if not skip_deterministic:
            drift = _trees_equal(after1, after2)
            if drift:
                _fail(
                    "API generation is not deterministic across consecutive runs.\n"
                    + "\n".join(drift[:20])
                )
            print("ok: API generation is deterministic")


def run_mint(script: str) -> None:
    """Run a mint CLI npm script from the website directory."""
    npm = shutil.which("npm")
    if npm is None:
        _fail("npm is required for Mintlify checks")
    mint_bin = WEBSITE / "node_modules" / ".bin" / "mint"
    if not mint_bin.exists():
        print("+ npm ci", flush=True)
        subprocess.run([npm, "ci"], check=True, cwd=WEBSITE)
    print(f"+ npm run {script}", flush=True)
    subprocess.run([npm, "run", script], check=True, cwd=WEBSITE)
    print(f"ok: mint {script}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-mint",
        action="store_true",
        help="Skip mint validate / broken-links (Python checks only)",
    )
    parser.add_argument(
        "--skip-deterministic",
        action="store_true",
        help="Skip the second regeneration pass",
    )
    parser.add_argument(
        "--mint-only",
        action="store_true",
        help="Only run Mintlify CLI checks",
    )
    args = parser.parse_args(argv)

    if not args.mint_only:
        check_docs_json()
        check_generated_banners()
        check_stale_and_deterministic(skip_deterministic=args.skip_deterministic)

    if not args.skip_mint:
        run_mint("validate")
        run_mint("broken-links")

    print("all website checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
