#!/usr/bin/env python3
"""Generate Mintlify MDX API reference from AgentConnect's public Python API.

Uses mdxify (Griffe-based) — no custom Python parser. Output is deterministic
and written only under website/python-api/ plus website/python-api-pages.json.
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
WEBSITE = Path(__file__).resolve().parents[1]
API_DIR = WEBSITE / "python-api"
NAV_FILE = WEBSITE / "python-api-pages.json"
HANDWRITTEN_API_INDEX = API_DIR / "index.mdx"

# Keep these modules out of the published reference (internal / optional plumbing).
# Mirror the spirit of MCP SDK EXCLUDED sets: public surface only.
EXCLUDE_PREFIXES = (
    "agentconnect.gateway",
    "agentconnect.utils",
    "agentconnect.index.registry.capability_discovery_impl",
)

GENERATED_BANNER = """\
{/* DO NOT EDIT. Generated by `make website-api` / website/scripts/generate_api.py.
    Handwritten docs live outside python-api/ (except python-api/index.mdx).
    Source: AgentConnect public Python modules via mdxify + Griffe 2. */}
"""

SOURCE_MARKER_RE = re.compile(
    r"\{/\* DO NOT EDIT\. Generated by.*?via mdxify \+ Griffe 2\. \*/\}\n?",
    re.DOTALL,
)

# Only fenced code is exempt from prose transforms.
_FENCE_PATTERN = re.compile(r"```[\s\S]*?```")
_RST_DOUBLE_TICK = re.compile(r"``([^`]+)``")
# Example URLs with HTML-escaped placeholders (from mdxify angle escaping).
_PLACEHOLDER_URL = re.compile(r"https?://\S*&lt;\S*")


def _transform_prose(prose: str) -> str:
    """Normalize RST ticks, wrap placeholder URLs, escape JSX braces."""
    prose = _RST_DOUBLE_TICK.sub(r"`\1`", prose)
    prose = _PLACEHOLDER_URL.sub(lambda m: f"`{m.group(0)}`", prose)
    return prose.replace("{", "&#123;").replace("}", "&#125;")


def _escape_mdx_braces(content: str) -> str:
    """Make generated Markdown safe for Mintlify's MDX parser.

    AgentConnect docstrings use RST double-backticks and dict literals.
    Transforms apply only outside ``` fences so signatures stay intact.
    """
    parts: list[str] = []
    last = 0
    for match in _FENCE_PATTERN.finditer(content):
        parts.append(_transform_prose(content[last : match.start()]))
        parts.append(match.group(0))
        last = match.end()
    parts.append(_transform_prose(content[last:]))
    return "".join(parts)


def _run_mdxify(repo_url: str, branch: str, docstring_style: str) -> None:
    """Invoke mdxify against the AgentConnect package."""
    # Wipe generated pages but keep the handwritten index.
    index_backup: str | None = None
    if HANDWRITTEN_API_INDEX.exists():
        index_backup = HANDWRITTEN_API_INDEX.read_text(encoding="utf-8")

    if API_DIR.exists():
        shutil.rmtree(API_DIR)
    API_DIR.mkdir(parents=True, exist_ok=True)

    if index_backup is not None:
        HANDWRITTEN_API_INDEX.write_text(index_backup, encoding="utf-8")

    cmd = [
        sys.executable,
        "-m",
        "mdxify",
        "--all",
        "--root-module",
        "agentconnect",
        "--output-dir",
        str(API_DIR),
        "--nav-output",
        str(NAV_FILE),
        "--repo-url",
        repo_url,
        "--branch",
        branch,
        "--docstring-style",
        docstring_style,
        "--format",
        "mdx",
    ]
    for prefix in EXCLUDE_PREFIXES:
        cmd.extend(["--exclude", prefix])

    env = os.environ.copy()
    # Stable timestamps / locale for deterministic generation where tools honor them.
    env.setdefault("TZ", "UTC")
    env.setdefault("LC_ALL", "C.UTF-8")
    env.setdefault("SOURCE_DATE_EPOCH", "0")

    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, cwd=ROOT, env=env)


def _postprocess_generated_files() -> None:
    """Escape MDX hazards and stamp every generated page with a do-not-edit banner."""
    for path in sorted(API_DIR.rglob("*.mdx")):
        if path.resolve() == HANDWRITTEN_API_INDEX.resolve():
            continue
        text = path.read_text(encoding="utf-8")
        text = SOURCE_MARKER_RE.sub("", text)

        # Escape braces in the body only; frontmatter has no `{` and must stay YAML.
        if text.startswith("---"):
            end = text.find("\n---", 3)
            if end != -1:
                end += len("\n---")
                front, body = text[:end], text[end:]
                text = front + _escape_mdx_braces(body)
            else:
                text = _escape_mdx_braces(text)
        else:
            text = _escape_mdx_braces(text)

        if text.startswith("---"):
            end = text.find("\n---", 3)
            if end != -1:
                end += len("\n---")
                stamped = text[:end] + "\n\n" + GENERATED_BANNER + text[end:].lstrip("\n")
                path.write_text(stamped, encoding="utf-8")
                continue
        path.write_text(GENERATED_BANNER + text, encoding="utf-8")


def _normalize_nav() -> None:
    """Ensure nav JSON ends with a trailing newline for stable git diffs."""
    raw = NAV_FILE.read_text(encoding="utf-8")
    if not raw.endswith("\n"):
        NAV_FILE.write_text(raw + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo-url",
        default="https://github.com/AKKI0511/AgentConnect",
        help="GitHub URL used for source links in generated pages",
    )
    parser.add_argument(
        "--branch",
        default="team-restructure",
        help="Git branch used for source links (product branch)",
    )
    parser.add_argument(
        "--docstring-style",
        default="google",
        choices=("google", "numpy", "sphinx"),
    )
    args = parser.parse_args(argv)

    _run_mdxify(args.repo_url, args.branch, args.docstring_style)
    _postprocess_generated_files()
    _normalize_nav()

    generated = sorted(
        p.relative_to(WEBSITE).as_posix()
        for p in API_DIR.rglob("*.mdx")
        if p.resolve() != HANDWRITTEN_API_INDEX.resolve()
    )
    print(f"Generated {len(generated)} API pages → {API_DIR.relative_to(ROOT)}/")
    print(f"Navigation → {NAV_FILE.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
