"""Core nouns: Message, Address, identity, Profile, kinds, and errors.

This package has no I/O and imports no sibling AgentConnect packages.
"""

from agentconnect.core.address import (
    ADDRESS_OUTSIDE_TEAM,
    INVALID_ADDRESS,
    ParsedAddress,
    parse_address,
    parse_agent_name,
    parse_team_name,
    resolve_address,
)
from agentconnect.core.exceptions import (
    AgentError,
    CapabilityError,
    CommunicationError,
    ConfigurationError,
    RegistrationError,
    SecurityError,
)
from agentconnect.core.identity import (
    AgentIdentity,
    AgentMetadata,
    JoinChallenge,
    MembershipAttestationClaims,
    VerificationStatus,
    decode_eddsa_jwt,
    did_key_from_public_bytes,
    encode_eddsa_jwt,
    is_ed25519_did_key,
    issue_identity_proof,
    issue_membership_attestation,
    public_bytes_from_did_key,
    public_key_pem_from_did,
    split_jwt,
    verify_identity_proof,
    verify_membership_attestation,
)
from agentconnect.core.kinds import (
    CONTROL_COOLDOWN,
    CONTROL_IGNORE,
    CONTROL_STOP,
    CONTROL_SYSTEM,
    MessageKind,
)
from agentconnect.core.message import Message
from agentconnect.core.profile import (
    AgentProfile,
    Capability,
    DirectoryEntry,
    DirectoryMatch,
    DiscoveryProfile,
    FindResult,
    Skill,
    SkillClaim,
    validate_discovery_profile,
)
from agentconnect.core.spec import SPEC_VERSION
from agentconnect.core.types import (
    AgentType,
    InteractionMode,
    NetworkMode,
    ProtocolVersion,
)

__all__ = [
    "ADDRESS_OUTSIDE_TEAM",
    "INVALID_ADDRESS",
    "ParsedAddress",
    "parse_address",
    "parse_agent_name",
    "parse_team_name",
    "resolve_address",
    "AgentError",
    "CapabilityError",
    "CommunicationError",
    "ConfigurationError",
    "RegistrationError",
    "SecurityError",
    "AgentIdentity",
    "AgentMetadata",
    "JoinChallenge",
    "MembershipAttestationClaims",
    "VerificationStatus",
    "decode_eddsa_jwt",
    "did_key_from_public_bytes",
    "encode_eddsa_jwt",
    "is_ed25519_did_key",
    "issue_identity_proof",
    "issue_membership_attestation",
    "public_bytes_from_did_key",
    "public_key_pem_from_did",
    "split_jwt",
    "verify_identity_proof",
    "verify_membership_attestation",
    "CONTROL_COOLDOWN",
    "CONTROL_IGNORE",
    "CONTROL_STOP",
    "CONTROL_SYSTEM",
    "MessageKind",
    "Message",
    "AgentProfile",
    "Capability",
    "DirectoryEntry",
    "DirectoryMatch",
    "DiscoveryProfile",
    "FindResult",
    "Skill",
    "SkillClaim",
    "validate_discovery_profile",
    "SPEC_VERSION",
    "AgentType",
    "InteractionMode",
    "NetworkMode",
    "ProtocolVersion",
]
