"""Name map from ``schema.ts`` definitions to Python types.

The round-trip test compares this map to ``schema.json``. Adding a public
type in TypeScript without a Python projection fails that test, and so
does a Python type whose fields drifted.
"""

from __future__ import annotations

from typing import Any

from agentconnect.core.base import JsonObject, JsonValue
from agentconnect.core.directory import (
    DirectoryEntry,
    DirectoryMatch,
    FindRequest,
    FindResult,
    GetProfileRequest,
)
from agentconnect.core.error import DeadlineExceededError, ErrorObject
from agentconnect.core.message import (
    Delivery,
    ErrorMessage,
    EventMessage,
    MailboxMessage,
    Message,
    RequestMessage,
    ResponseMessage,
)
from agentconnect.core.operations import (
    AcceptedSendResult,
    AddressCallbackTarget,
    AskToolRequest,
    CallbackTarget,
    CompleteRequest,
    CompleteResult,
    EventSendRequest,
    GetHistoryRequest,
    GetResultRequest,
    HeartbeatResult,
    HistoryResult,
    IssueJoinTokenRequest,
    JoinChallenge,
    JoinRequest,
    JoinResult,
    JoinTokenIssued,
    LeaseRequest,
    LeaseResult,
    ReplyFailureRequest,
    ReplyRequest,
    ReplyResult,
    ReplySuccessRequest,
    RequestSendRequest,
    RevokeJoinTokenRequest,
    RuntimeEvent,
    RuntimeLimits,
    SendRequest,
    SendResult,
    StatusMember,
    StatusResult,
    TeamRoster,
    TellToolRequest,
    TicketedSendResult,
    ToolErrorResult,
    TraceEvent,
    TraceResult,
    UrlCallbackTarget,
)
from agentconnect.core.primitives import (
    Address,
    AgentDid,
    AgentName,
    CollectMode,
    DeliveryHistoryForm,
    ErrorCode,
    PersistenceMode,
    QualifiedAddress,
    SessionToken,
    SkillExample,
    SpecVersion,
    Tag,
    TeamName,
    TicketState,
    Timestamp,
    TraceEventType,
    Uuid,
)
from agentconnect.core.profile import AgentProfile, Skill
from agentconnect.core.ticket import (
    CompletedTicket,
    DeclinedTicket,
    ExpiredTicket,
    FailedTicket,
    OpenTicket,
    Ticket,
)

# Every schema.json definition except the generation wrapper.
PUBLIC_SCHEMA_TYPES: dict[str, Any] = {
    "SpecVersion": SpecVersion,
    "Timestamp": Timestamp,
    "Uuid": Uuid,
    "AgentName": AgentName,
    "TeamName": TeamName,
    "Address": Address,
    "QualifiedAddress": QualifiedAddress,
    "AgentDid": AgentDid,
    "SessionToken": SessionToken,
    "JsonValue": JsonValue,
    "JsonObject": JsonObject,
    "PersistenceMode": PersistenceMode,
    "CollectMode": CollectMode,
    "DeliveryHistoryForm": DeliveryHistoryForm,
    "TicketState": TicketState,
    "ErrorCode": ErrorCode,
    "Tag": Tag,
    "SkillExample": SkillExample,
    "Skill": Skill,
    "AgentProfile": AgentProfile,
    "ErrorObject": ErrorObject,
    "DeadlineExceededError": DeadlineExceededError,
    "RequestMessage": RequestMessage,
    "EventMessage": EventMessage,
    "MailboxMessage": MailboxMessage,
    "ResponseMessage": ResponseMessage,
    "ErrorMessage": ErrorMessage,
    "Message": Message,
    "Delivery": Delivery,
    "OpenTicket": OpenTicket,
    "CompletedTicket": CompletedTicket,
    "FailedTicket": FailedTicket,
    "ExpiredTicket": ExpiredTicket,
    "DeclinedTicket": DeclinedTicket,
    "Ticket": Ticket,
    "DirectoryEntry": DirectoryEntry,
    "DirectoryMatch": DirectoryMatch,
    "JoinChallenge": JoinChallenge,
    "JoinRequest": JoinRequest,
    "RuntimeLimits": RuntimeLimits,
    "JoinResult": JoinResult,
    "HeartbeatResult": HeartbeatResult,
    "CallbackTarget": CallbackTarget,
    "RequestSendRequest": RequestSendRequest,
    "EventSendRequest": EventSendRequest,
    "SendRequest": SendRequest,
    "AcceptedSendResult": AcceptedSendResult,
    "TicketedSendResult": TicketedSendResult,
    "SendResult": SendResult,
    "LeaseRequest": LeaseRequest,
    "LeaseResult": LeaseResult,
    "CompleteRequest": CompleteRequest,
    "CompleteResult": CompleteResult,
    "ReplySuccessRequest": ReplySuccessRequest,
    "ReplyFailureRequest": ReplyFailureRequest,
    "ReplyRequest": ReplyRequest,
    "ReplyResult": ReplyResult,
    "GetResultRequest": GetResultRequest,
    "GetHistoryRequest": GetHistoryRequest,
    "HistoryResult": HistoryResult,
    "FindRequest": FindRequest,
    "FindResult": FindResult,
    "GetProfileRequest": GetProfileRequest,
    "AskToolRequest": AskToolRequest,
    "TellToolRequest": TellToolRequest,
    "TeamRoster": TeamRoster,
    "TraceEventType": TraceEventType,
    "TraceEvent": TraceEvent,
    "TraceResult": TraceResult,
    "StatusMember": StatusMember,
    "StatusResult": StatusResult,
    "IssueJoinTokenRequest": IssueJoinTokenRequest,
    "JoinTokenIssued": JoinTokenIssued,
    "RevokeJoinTokenRequest": RevokeJoinTokenRequest,
    "RuntimeEvent": RuntimeEvent,
    "ToolErrorResult": ToolErrorResult,
}

# Present in schema.json as a generation root, not an exchanged object.
SCHEMA_WRAPPER_NAME = "AgentConnectPublicSchema"

# Union members that exist only as Python classes for CallbackTarget.
CALLBACK_TARGET_VARIANTS = (AddressCallbackTarget, UrlCallbackTarget)
